# CROSS VALIDATE L1B OUTPUTS EQUALIZED

# PLOT FROM YOUR OUTPUTS THE EQUALISED OUTPUT VERSUS NOT EQUALISED VERSUS THE TRUTH
# TRUTH = EODP-TS-L1B\input\ism_toa_isrf_VNIR-0.nc

# TO DO : Generate script that iterates and compares output files with each other ( Outputs-Output equalized-Output not equalized)
# EXPLAIN THE PLOT FIGURE 8_3 IN THE THEORY PDF , WHY BLACK LINE IS NOT BLUE LINE , THAT IS IN THE DELIVERABLE REPORT

# EXPLANATION GUIDELINE : AN INSTRUMENT IS A THING THAT RECORDS ENERGY , IN OUR CASE WE HAVE MLI MULTIBAND IMAGER , INCOMING LIGHT IN TELESPCPOE GETS THROUGH MIRRORS REACHES DETECTOR , WE ARE ACQUIRING INFO IN PARTS OF THE SPECTRUM , RECORDING INFO ,
# AND THEN WE HAVE THE DETECTION SYSTEM WHICH DIGITIZES AND RECORDS , OUR SYS IS NOT PERFECT , WE HAVE NO PERFECT FILTER , THERE ARE NOISES ,  IN ORDER TO UNDERSTAND HOW SYS BEHAVES WE CALIBRATE PERIODICALLY , BLUE LINE IS THE ACTUAL ENERGY THAT ARRIVES TO INSTRUMENT .
# IT IS THE TRUTH ^ . THE RED LINE IS THE ACTUAL OUTPUT IF YOU DO NOT CALIBRATE IMAGE , BLACK LINE IS THE RESPONSE IF YOU CALIBRATED OUTPUT. WE TRY TO GET AS CLOSE AS POSSIBLE TO TRUTH BUT THERE IS SLIGHT DELTA DIFFERENCE , IT DECLARES HOW MUCH SYS NOISE WE HAVE  